apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: setlist-search
  annotations:
    kubernetes.io/ingress.global-static-ip-name: setlist-search-ip
  labels:
    app: setlist-search
spec:
  backend:
    serviceName: setlist-search-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: setlist-search-backend
  labels:
    app: setlist-search
spec:
  type: NodePort
  selector:
    app: setlist-search
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
