apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: searchphish
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: http,https
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: setlist-search
          servicePort: 8080
